/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package paintbasico;

import java.awt.event.ActionEvent;
import java.io.File;
import sm.sound.SMClipPlayer;
import sm.sound.SMPlayer;

/**
 *
 * @author David
 */
public class VentanaInternaReproductor extends javax.swing.JInternalFrame {
    private SMPlayer player = null;

    @Override
    public void dispose() {
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
        player.stop();
    }
    /**
     * Creates new form VentanaInternaReproductor
     */
    public VentanaInternaReproductor(File f) {
        initComponents();
        player = new SMClipPlayer(f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonPlay = new javax.swing.JButton();
        botonStop = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.FlowLayout());

        botonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/audio/PlayPressed_48x48.png"))); // NOI18N
        botonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPlayActionPerformed(evt);
            }
        });
        getContentPane().add(botonPlay);

        botonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/audio/StopDisabled_48x48.png"))); // NOI18N
        botonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonStopActionPerformed(evt);
            }
        });
        getContentPane().add(botonStop);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPlayActionPerformed
        if (player != null) {
            player.play();
        }
    }//GEN-LAST:event_botonPlayActionPerformed

    private void botonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonStopActionPerformed
        if (player != null) {
            player.stop();
        }
    }//GEN-LAST:event_botonStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPlay;
    private javax.swing.JButton botonStop;
    // End of variables declaration//GEN-END:variables
}
